(function installGraphCore(root){
  const CODE={
    DUPLICATE_NODE_ID:'GRAPH_DUPLICATE_NODE_ID',DUPLICATE_EDGE_ID:'GRAPH_DUPLICATE_EDGE_ID',
    UNKNOWN_DEFINITION:'GRAPH_UNKNOWN_DEFINITION',INVALID_POSITION:'GRAPH_INVALID_POSITION',
    DANGLING_EDGE:'GRAPH_DANGLING_EDGE',UNKNOWN_SOURCE_PORT:'GRAPH_UNKNOWN_SOURCE_PORT',
    UNKNOWN_TARGET_PORT:'GRAPH_UNKNOWN_TARGET_PORT',TYPE_MISMATCH:'GRAPH_TYPE_MISMATCH',
    SINGLE_INPUT_MULTIPLE_EDGES:'GRAPH_SINGLE_INPUT_MULTIPLE_EDGES',REQUIRED_INPUT_MISSING:'GRAPH_REQUIRED_INPUT_MISSING',
    CYCLE_DETECTED:'GRAPH_CYCLE_DETECTED',DEFINITION_VERSION_MISSING:'GRAPH_DEFINITION_VERSION_MISSING',
    PLUGIN_EXECUTOR_MISSING:'GRAPH_PLUGIN_EXECUTOR_MISSING',PLUGIN_DEPENDENCY_MISSING:'GRAPH_PLUGIN_DEPENDENCY_MISSING',
    PLUGIN_DEPENDENCY_MISMATCH:'GRAPH_PLUGIN_DEPENDENCY_MISMATCH'
  };
  const issue=(code,message,extra={})=>({code,severity:'error',message,...extra});
  const compatible=(sourceType,targetType)=>sourceType===targetType||targetType==='artifact.any';
  function duplicateIssues(items,key,code,label){const seen=new Set(),issues=[];for(const item of items||[]){const value=item?.[key];if(!value||seen.has(value))issues.push(issue(code,`${label} ${value||'(empty)'} 重复或为空`,{path:`${label}.${key}`}));else seen.add(value)}return issues}
  function cycleNodeIds(nodes,edges){const active=nodes.filter(n=>!n.disabled),ids=new Set(active.map(n=>n.id)),adj=new Map(active.map(n=>[n.id,[]]));for(const edge of edges.filter(e=>!e.disabled&&ids.has(e.source)&&ids.has(e.target)))adj.get(edge.source).push(edge.target);const visiting=new Set(),visited=new Set(),stack=[];let cycle=[];const visit=id=>{if(visiting.has(id)){cycle=stack.slice(stack.indexOf(id)).concat(id);return true}if(visited.has(id))return false;visiting.add(id);stack.push(id);for(const next of adj.get(id)||[])if(visit(next))return true;stack.pop();visiting.delete(id);visited.add(id);return false};for(const node of active)if(visit(node.id))break;return cycle}
  function validateWorkflow(catalog,workflow,options={}){
    const issues=[],definitions=catalog?.definitions||[],definitionMap=new Map(definitions.map(d=>[d.id,d])),nodes=workflow?.nodes||[],edges=workflow?.edges||[],nodeMap=new Map(nodes.map(n=>[n.id,n]));
    issues.push(...duplicateIssues(nodes,'id',CODE.DUPLICATE_NODE_ID,'node'),...duplicateIssues(edges,'id',CODE.DUPLICATE_EDGE_ID,'edge'));
    for(const node of nodes){const definition=definitionMap.get(node.definitionId);if(!definition){issues.push(issue(CODE.UNKNOWN_DEFINITION,`节点 ${node.id} 引用未知定义 ${node.definitionId}`,{nodeId:node.id,path:`nodes.${node.id}.definitionId`}));continue}if(!definition.version)issues.push(issue(CODE.DEFINITION_VERSION_MISSING,`节点定义 ${definition.id} 缺少版本`,{nodeId:node.id,path:`definitions.${definition.id}.version`}));if(definition.source==='plugin'&&!definition.executorRef)issues.push(issue(CODE.PLUGIN_EXECUTOR_MISSING,`插件节点 ${definition.title||definition.id} 缺少 Executor Ref`,{nodeId:node.id,path:`definitions.${definition.id}.executorRef`}));if(!node.position||!Number.isFinite(node.position.x)||!Number.isFinite(node.position.y))issues.push(issue(CODE.INVALID_POSITION,`节点 ${node.id} 缺少合法位置`,{nodeId:node.id,path:`nodes.${node.id}.position`}))}
    const connectedInputs=new Map();
    for(const edge of edges){const sourceNode=nodeMap.get(edge.source),targetNode=nodeMap.get(edge.target);if(!sourceNode||!targetNode){issues.push(issue(CODE.DANGLING_EDGE,`连线 ${edge.id} 引用不存在节点`,{edgeId:edge.id,path:`edges.${edge.id}`}));continue}const sourceDefinition=definitionMap.get(sourceNode.definitionId),targetDefinition=definitionMap.get(targetNode.definitionId),sourcePort=sourceDefinition?.outputs?.find(p=>p.id===edge.sourcePort),targetPort=targetDefinition?.inputs?.find(p=>p.id===edge.targetPort);if(!sourcePort)issues.push(issue(CODE.UNKNOWN_SOURCE_PORT,`连线 ${edge.id} 未找到输出端口 ${edge.source}.${edge.sourcePort}`,{edgeId:edge.id,nodeId:edge.source,path:`edges.${edge.id}.sourcePort`}));if(!targetPort)issues.push(issue(CODE.UNKNOWN_TARGET_PORT,`连线 ${edge.id} 未找到输入端口 ${edge.target}.${edge.targetPort}`,{edgeId:edge.id,nodeId:edge.target,path:`edges.${edge.id}.targetPort`}));if(sourcePort&&targetPort&&!compatible(sourcePort.type,targetPort.type))issues.push(issue(CODE.TYPE_MISMATCH,`连线 ${edge.id} 类型不兼容 ${sourcePort.type} → ${targetPort.type}`,{edgeId:edge.id,nodeId:edge.target,path:`edges.${edge.id}`}));if(edge.disabled||sourceNode.disabled||targetNode.disabled||!targetPort)continue;const binding=`${edge.target}:${edge.targetPort}`,count=(connectedInputs.get(binding)||0)+1;connectedInputs.set(binding,count);if(targetPort.cardinality==='one'&&count>1)issues.push(issue(CODE.SINGLE_INPUT_MULTIPLE_EDGES,`单值输入 ${binding} 被重复连接`,{edgeId:edge.id,nodeId:edge.target,path:`nodes.${edge.target}.inputs.${edge.targetPort}`}))}
    for(const node of nodes.filter(n=>!n.disabled)){const definition=definitionMap.get(node.definitionId);for(const input of definition?.inputs||[]){if(input.required&&!connectedInputs.has(`${node.id}:${input.id}`)&&node.config?.[input.id]===undefined)issues.push(issue(CODE.REQUIRED_INPUT_MISSING,`必填输入未连接 ${node.id}.${input.id}（${definition.title||definition.id}）`,{nodeId:node.id,path:`nodes.${node.id}.inputs.${input.id}`}))}}
    const cycle=cycleNodeIds(nodes,edges);if(cycle.length)issues.push(issue(CODE.CYCLE_DETECTED,`检测到未声明环路：${cycle.join(' → ')}`,{nodeId:cycle[0],path:'edges'}));
    if(options.requirePluginDependencies){const dependencyMap=new Map((workflow.pluginDependencies||[]).map(d=>[d.definitionId,d]));for(const node of nodes.filter(n=>!n.disabled)){const definition=definitionMap.get(node.definitionId);if(definition?.source!=='plugin')continue;const dependency=dependencyMap.get(definition.id);if(!dependency)issues.push(issue(CODE.PLUGIN_DEPENDENCY_MISSING,`插件 ${definition.id} 缺少发布依赖锁`,{nodeId:node.id,path:'pluginDependencies'}));else if(dependency.version!==definition.version||dependency.executorRef!==definition.executorRef)issues.push(issue(CODE.PLUGIN_DEPENDENCY_MISMATCH,`插件 ${definition.id} 的依赖版本或执行路由不匹配`,{nodeId:node.id,path:`pluginDependencies.${definition.id}`}))}}
    return issues;
  }
  root.GraphCore=Object.freeze({CODE,compatible,validateWorkflow});
})(globalThis);
